name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
        id: go
      - name: checkout
        uses: actions/checkout@v3
      - name: modules
        run: go mod download
      - name: test
        run: go test -v ./emf
